### PR TITLE
Migrate to yarn berry

### PR DESCRIPTION
**Pull request by lesser1**
Issue link: https://frontend.gropius.duckdns.org/components/9d12d6ac-e85a-407c-bdff-a8321fb75d3a/issues/72e20bfc-48e8-4eec-afe0-2b967cb127a9

### CODE REVIEW

**Comment by lesser1** [comment]
The GitHub Action "Build and Lint and Format" (https://github.com/MiSArch/frontend/actions/workflows/build_lint_format.yml) must be updated first before this PR can be merged.

**Comment by nk-coding** [comment]
> The GitHub Action "Build and Lint and Format" (https://github.com/MiSArch/frontend/actions/workflows/build_lint_format.yml) must be updated first before this PR can be merged.

do you plan to do this as part of this PR?

**Comment by lesser1** [comment]
> > The GitHub Action "Build and Lint and Format" (https://github.com/MiSArch/frontend/actions/workflows/build_lint_format.yml) must be updated first before this PR can be merged.
> 
> do you plan to do this as part of this PR?

Opened another PR for that (see https://github.com/MiSArch/frontend/pull/10). I already merged it to save you & us and some time...

**Review by nk-coding — APPROVED** [review]
Well then merge main in this branch and we see if it works

**Pull request merged**
